package com.justbash.interpreter.expansion

import com.justbash.ast.*

fun globPatternHasVarRef(pattern: String): Boolean { var i = 0; while (i < pattern.length) { if (pattern[i] == '\\') { i += 2; continue }; if (pattern[i] == '$') { val next = pattern.getOrNull(i + 1); if (next == '{' || (next != null && next.isLetter())) return true }; i++ }; return false }
private fun hasQuotedOperationWord(part: ParameterExpansionPart): Boolean { val op = part.operation ?: return false; val wordParts: List<WordPart>? = when (op) { is DefaultValueOp -> op.word.parts; is AssignDefaultOp -> op.word.parts; is UseAlternativeOp -> op.word.parts; is ErrorIfUnsetOp -> op.word?.parts; else -> null }; return wordParts?.any { it is DoubleQuotedPart || it is SingleQuotedPart } ?: false }
fun isOperationWordEntirelyQuoted(part: ParameterExpansionPart): Boolean { val op = part.operation ?: return false; val wordParts: List<WordPart>? = when (op) { is DefaultValueOp -> op.word.parts; is AssignDefaultOp -> op.word.parts; is UseAlternativeOp -> op.word.parts; is ErrorIfUnsetOp -> op.word?.parts; else -> null }; if (wordParts.isNullOrEmpty()) return false; return wordParts.all { it is DoubleQuotedPart || it is SingleQuotedPart } }
data class WordPartsAnalysis(var hasQuoted: Boolean = false, var hasCommandSub: Boolean = false, var hasArrayVar: Boolean = false, var hasArrayAtExpansion: Boolean = false, var hasParamExpansion: Boolean = false, var hasVarNamePrefixExpansion: Boolean = false, var hasIndirection: Boolean = false)
fun analyzeWordParts(parts: List<WordPart>): WordPartsAnalysis { val result = WordPartsAnalysis(); for (part in parts) { if (part is SingleQuotedPart || part is DoubleQuotedPart) { result.hasQuoted = true; if (part is DoubleQuotedPart) { for (inner in part.parts) { if (inner is ParameterExpansionPart) { val match = Regex("^([a-zA-Z_][a-zA-Z0-9_]*)\\[[@*]\\]$").find(inner.parameter); if (match != null && (inner.operation == null || inner.operation is PatternRemovalOp || inner.operation is PatternReplacementOp)) result.hasArrayAtExpansion = true; if (inner.operation is VarNamePrefixOp || inner.operation is ArrayKeysOp) result.hasVarNamePrefixExpansion = true; if (inner.operation is IndirectionOp) result.hasIndirection = true } } } }; if (part is CommandSubstitutionPart) result.hasCommandSub = true; if (part is ParameterExpansionPart) { result.hasParamExpansion = true; if (part.parameter == "@" || part.parameter == "*") result.hasArrayVar = true; if (hasQuotedOperationWord(part)) result.hasQuoted = true; if (part.operation is VarNamePrefixOp || part.operation is ArrayKeysOp) result.hasVarNamePrefixExpansion = true; if (part.operation is IndirectionOp) result.hasIndirection = true }; if (part is GlobPart && globPatternHasVarRef(part.pattern)) result.hasParamExpansion = true }; return result }
