package com.justbash.interpreter.expansion

import com.justbash.encoding.Encoding

private const val MAX_SAFE_RANGE_ITERATIONS = 10000
data class BraceRangeLimits(val maxResults: Int = MAX_SAFE_RANGE_ITERATIONS, val maxStringBytes: Int = 10 * 1024 * 1024)
data class BraceRangeResult(val expanded: List<String>?, val literal: String)
private class ByteCounter(var value: Int = 0)
private fun pushRangeValue(results: ArrayList<String>, value: String, limits: BraceRangeLimits, ab: ByteCounter): Boolean { if (results.size >= limits.maxResults) return false; val bytes = Encoding.utf8ByteLength(value); if (bytes > limits.maxStringBytes - ab.value) throw ExecutionLimitError("brace expansion string limit exceeded (${limits.maxStringBytes} bytes)", "string_length"); results.add(value); ab.value += bytes; return true }
private fun safeExpandNumericRange(start: Int, end: Int, rawStep: Int?, startStr: String?, endStr: String?, limits: BraceRangeLimits): List<String>? { var step = rawStep ?: 1; if (step == 0) step = 1; val absStep = Math.abs(step); var padWidth = 0; if (startStr != null && startStr.matches(Regex("^-?0\\d"))) padWidth = Math.max(padWidth, startStr.replace(Regex("^-"), "").length); if (endStr != null && endStr.matches(Regex("^-?0\\d"))) padWidth = Math.max(padWidth, endStr.replace(Regex("^-"), "").length); if (padWidth > limits.maxStringBytes) throw ExecutionLimitError("brace expansion padding limit exceeded (${limits.maxStringBytes} bytes)", "string_length"); val ab = ByteCounter(); fun fmt(n: Int): String { if (padWidth > 0) { val neg = n < 0; val absStr = Math.abs(n).toString().padStart(padWidth, '0'); return if (neg) "-$absStr" else absStr }; return n.toString() }; val results = ArrayList<String>(); if (start <= end) { var i = start; var count = 0; while (i <= end && count < MAX_SAFE_RANGE_ITERATIONS) { if (!pushRangeValue(results, fmt(i), limits, ab)) break; i += absStep; count++ } } else { var i = start; var count = 0; while (i >= end && count < MAX_SAFE_RANGE_ITERATIONS) { if (!pushRangeValue(results, fmt(i), limits, ab)) break; i -= absStep; count++ } }; return results }
private fun safeExpandCharRange(start: String, end: String, rawStep: Int?, limits: BraceRangeLimits): List<String>? { var step = rawStep ?: 1; if (step == 0) step = 1; val absStep = Math.abs(step); val sCode = start[0].code; val eCode = end[0].code; val sU = start[0] in 'A'..'Z'; val sL = start[0] in 'a'..'z'; val eU = end[0] in 'A'..'Z'; val eL = end[0] in 'a'..'z'; if ((sU && eL) || (sL && eU)) { val sp = if (rawStep != null) "..$rawStep" else ""; throw BraceExpansionError("{${start}..${end}$sp}: invalid sequence") }; val results = ArrayList<String>(); val ab = ByteCounter(); if (sCode <= eCode) { var i = sCode; var count = 0; while (i <= eCode && count < MAX_SAFE_RANGE_ITERATIONS) { if (!pushRangeValue(results, StringBuilder().appendCodePoint(i).toString(), limits, ab)) break; i += absStep; count++ } } else { var i = sCode; var count = 0; while (i >= eCode && count < MAX_SAFE_RANGE_ITERATIONS) { if (!pushRangeValue(results, StringBuilder().appendCodePoint(i).toString(), limits, ab)) break; i -= absStep; count++ } }; return results }
fun expandBraceRange(start: Any, end: Any, step: Int?, startStr: String? = null, endStr: String? = null, limits: BraceRangeLimits = BraceRangeLimits()): BraceRangeResult { val stepPart = if (step != null) "..$step" else ""; if (start is Int && end is Int) { val expanded = safeExpandNumericRange(start, end, step, startStr, endStr, limits); return BraceRangeResult(expanded, "{${start}..${end}$stepPart}") }; if (start is String && end is String) { val expanded = safeExpandCharRange(start, end, step, limits); return BraceRangeResult(expanded, "{${start}..${end}$stepPart}") }; return BraceRangeResult(null, "{${start}..${end}$stepPart}") }
