package com.justbash.interpreter.expansion

import com.justbash.ast.*

private fun checkStringLength(str: String, maxLength: Int, context: String) { if (str.length > maxLength) throw ExecutionLimitError("$context: string length limit exceeded ($maxLength bytes)", "string_length") }
fun expandPart(ctx: ExpansionContext, part: WordPart, inDoubleQuotes: Boolean = false): String {
    if (part is ParameterExpansionPart) return expandParameter(ctx, part, inDoubleQuotes)
    val literal = getLiteralValue(part); if (literal != null) return literal
    when (part) {
        is TildeExpansionPart -> { if (inDoubleQuotes) return if (part.user == null) "~" else "~${part.user}"; if (part.user == null) return ctx.state.env["HOME"] ?: "/home/user"; if (part.user == "root") return "/root"; return "~${part.user}" }
        is GlobPart -> return expandVariablesInPattern(ctx, part.pattern)
        is DoubleQuotedPart -> return part.parts.joinToString("") { expandPart(ctx, it, true) }
        is CommandSubstitutionPart -> return expandCmdSubst(ctx, part)
        is ArithmeticExpansionPart -> return formatArith(evaluateArithmetic(ctx, part.expression.expression, true)).toString()
        is BraceExpansionPart -> { val results = ArrayList<String>(); for (item in part.items) { when (item) { is BraceRangeItem -> { val range = expandBraceRange(item.start, item.end, item.step, item.startStr, item.endStr, BraceRangeLimits(ctx.limits.maxBraceExpansionResults, ctx.limits.maxStringLength)); if (range.expanded != null) results.addAll(range.expanded) else return range.literal }; is BraceWordItem -> results.add(expandWord(ctx, item.word)) } }; return results.joinToString(" ") }
        else -> return ""
    }
}
fun expandWord(ctx: ExpansionContext, word: WordNode): String { val parts = word.parts; if (parts.size == 1) { val r = expandPart(ctx, parts[0]); checkStringLength(r, ctx.limits.maxStringLength, "word expansion"); return r }; val r = parts.joinToString("") { expandPart(ctx, it) }; checkStringLength(r, ctx.limits.maxStringLength, "word expansion"); return r }
fun expandWordParts(ctx: ExpansionContext, parts: List<WordPart>, inDoubleQuotes: Boolean = false): String = parts.joinToString("") { expandPart(ctx, it, inDoubleQuotes) }
private fun expandCmdSubst(ctx: ExpansionContext, part: CommandSubstitutionPart): String { val cd = ctx.substitutionDepth; val md = ctx.limits.maxSubstitutionDepth; if (cd >= md) throw ExecutionLimitError("Command substitution nesting limit exceeded ($md)", "substitution_depth"); ctx.substitutionDepth = cd + 1; val sb = ctx.state.bashPid; ctx.state.bashPid = ctx.state.nextVirtualPid++; val se = LinkedHashMap(ctx.state.env); val sa = cloneArrays(ctx.state.arrays); val sc = ctx.state.cwd; val sv = ctx.state.suppressVerbose; ctx.state.suppressVerbose = true; try { val r = ctx.executeScript(part.body); ctx.state.env.clear(); ctx.state.env.putAll(se); ctx.state.arrays.clear(); ctx.state.arrays.putAll(sa); ctx.state.cwd = sc; ctx.state.suppressVerbose = sv; ctx.state.lastExitCode = r.exitCode; ctx.state.env["?"] = r.exitCode.toString(); if (r.stderr.isNotEmpty()) ctx.state.expansionStderr += r.stderr; ctx.state.bashPid = sb; ctx.substitutionDepth = cd; val o = r.stdout.replace(Regex("\\n+\$"), ""); checkStringLength(o, ctx.limits.maxStringLength, "command substitution"); return o } catch (e: Exception) { ctx.state.env.clear(); ctx.state.env.putAll(se); ctx.state.arrays.clear(); ctx.state.arrays.putAll(sa); ctx.state.cwd = sc; ctx.state.bashPid = sb; ctx.substitutionDepth = cd; ctx.state.suppressVerbose = sv; if (e is ExecutionLimitError) throw e; if (e is ExitError) { ctx.state.lastExitCode = e.exitCode; ctx.state.env["?"] = e.exitCode.toString(); if (e.stderr.isNotEmpty()) ctx.state.expansionStderr += e.stderr; return e.stdout.replace(Regex("\\n+\$"), "") }; throw e } }
fun expandParameter(ctx: ExpansionContext, part: ParameterExpansionPart, inDoubleQuotes: Boolean = false): String { var parameter = part.parameter; val operation = part.operation; val skipNounset = operation != null && (operation is DefaultValueOp || operation is AssignDefaultOp || operation is UseAlternativeOp || operation is ErrorIfUnsetOp); val value = getVariable(ctx, parameter, !skipNounset); if (operation == null) return value; val isUnset = !isVariableSet(ctx, parameter); val (isEmpty, effectiveValue) = computeIsEmpty(ctx, parameter, value, inDoubleQuotes); val opCtx = ParameterOpContext(value, isUnset, isEmpty, effectiveValue, inDoubleQuotes); return when (operation) { is DefaultValueOp -> handleDefaultValue(ctx, operation, opCtx, ::expandWordParts); is AssignDefaultOp -> handleAssignDefault(ctx, parameter, operation, opCtx, ::expandWordParts); is ErrorIfUnsetOp -> handleErrorIfUnset(ctx, parameter, operation, opCtx, ::expandWordParts); is UseAlternativeOp -> handleUseAlternative(ctx, operation, opCtx, ::expandWordParts); is PatternRemovalOp -> { val r = handlePatternRemoval(ctx, value, operation, ::expandWordParts, ::expandPart); checkStringLength(r, ctx.limits.maxStringLength, "pattern removal"); r }; is PatternReplacementOp -> { val r = handlePatternReplacement(ctx, value, operation, ::expandWordParts, ::expandPart); checkStringLength(r, ctx.limits.maxStringLength, "pattern replacement"); r }; is LengthOp -> handleLength(ctx, parameter, value); is LengthSliceErrorOp -> throw BadSubstitutionError(parameter); is BadSubstitutionOp -> throw BadSubstitutionError(operation.text); is SubstringOp -> handleSubstring(ctx, parameter, value, operation); is CaseModificationOp -> { val r = handleCaseModification(ctx, value, operation, ::expandWordParts, ::expandParameter); checkStringLength(r, ctx.limits.maxStringLength, "case modification"); r }; is TransformOp -> handleTransform(ctx, parameter, value, isUnset, operation); is IndirectionOp -> handleIndirection(ctx, parameter, value, isUnset, operation, ::expandParameter, inDoubleQuotes); is ArrayKeysOp -> handleArrayKeys(ctx, operation); is VarNamePrefixOp -> handleVarNamePrefix(ctx, operation); else -> value } }
internal fun expandVariablesInPattern(ctx: ExpansionContext, pattern: String): String { var result = ""; var i = 0; while (i < pattern.length) { val c = pattern[i]; when { c == '\'' -> { val ci = pattern.indexOf('\'', i + 1); if (ci != -1) { result += escapeGlobChars(pattern.substring(i + 1, ci)); i = ci + 1; continue } }; c == '"' -> { var ci = -1; var j = i + 1; while (j < pattern.length) { if (pattern[j] == '\\') { j += 2; continue }; if (pattern[j] == '"') { ci = j; break }; j++ }; if (ci != -1) { result += escapeGlobChars(expandVarsInDqPattern(ctx, pattern.substring(i + 1, ci))); i = ci + 1; continue } }; c == '$' && i + 1 < pattern.length -> { val next = pattern[i + 1]; if (next == '{') { val ci = pattern.indexOf('}', i + 2); if (ci != -1) { result += ctx.state.env[pattern.substring(i + 2, ci)] ?: ""; i = ci + 1; continue } } else if (next.isLetter()) { var end = i + 1; while (end < pattern.length && pattern[end].isLetterOrDigit()) end++; result += ctx.state.env[pattern.substring(i + 1, end)] ?: ""; i = end; continue } }; c == '\\' && i + 1 < pattern.length -> { result += c.toString() + pattern[i + 1]; i += 2; continue } }; result += c; i++ }; return result }
private fun expandVarsInDqPattern(ctx: ExpansionContext, content: String): String { var result = ""; var i = 0; while (i < content.length) { val c = content[i]; if (c == '\\' && i + 1 < content.length) { val next = content[i + 1]; if (next == '$' || next == '`' || next == '\\' || next == '"') { result += next; i += 2; continue }; result += c; i++; continue }; if (c == '$' && i + 1 < content.length) { val next = content[i + 1]; if (next == '{') { val ci = content.indexOf('}', i + 2); if (ci != -1) { result += ctx.state.env[content.substring(i + 2, ci)] ?: ""; i = ci + 1; continue } } else if (next.isLetter()) { var end = i + 1; while (end < content.length && content[end].isLetterOrDigit()) end++; result += ctx.state.env[content.substring(i + 1, end)] ?: ""; i = end; continue } }; result += c; i++ }; return result }
