package com.justbash.interpreter.expansion

import com.justbash.ast.*

typealias ExpandWordPartsFn = (ctx: ExpansionContext, parts: List<WordPart>, inDoubleQuotes: Boolean) -> String
typealias ExpandPartFn = (ctx: ExpansionContext, part: WordPart, inDoubleQuotes: Boolean) -> String
typealias ExpandParameterFn = (ctx: ExpansionContext, part: ParameterExpansionPart, inDoubleQuotes: Boolean) -> String

data class ParameterOpContext(val value: String, val isUnset: Boolean, val isEmpty: Boolean, val effectiveValue: String, val inDoubleQuotes: Boolean)

fun computeIsEmpty(ctx: ExpansionContext, parameter: String, value: String, inDoubleQuotes: Boolean): Pair<Boolean, String> { val numParams = (ctx.state.env["#"] ?: "0").toIntOrNull() ?: 0; val aem = Regex("^([a-zA-Z_][a-zA-Z0-9_]*)\\[([@*])\\]$").find(parameter); if (parameter == "*") return (numParams == 0) to value; if (parameter == "@") { val ie = numParams == 0 || (numParams == 1 && ctx.state.env["1"] == ""); return ie to value }; if (aem != null) { val an = aem.groupValues[1]; val sub = aem.groupValues[2]; val els = getArrayElements(ctx, an); if (els.isEmpty()) return true to ""; if (sub == "*") { val ifsSep = getIfsSeparator(ctx.state.env); val joined = els.joinToString(ifsSep) { (_, v) -> v }; return (if (inDoubleQuotes) joined == "" else false) to joined }; val ie = els.size == 1 && els.all { (_, v) -> v == "" }; return ie to els.joinToString(" ") { (_, v) -> v } }; return (value == "") to value }

fun handleDefaultValue(ctx: ExpansionContext, operation: DefaultValueOp, opCtx: ParameterOpContext, ewp: ExpandWordPartsFn): String { val ud = opCtx.isUnset || (operation.checkEmpty && opCtx.isEmpty); return if (ud) ewp(ctx, operation.word.parts, opCtx.inDoubleQuotes) else opCtx.effectiveValue }
fun handleAssignDefault(ctx: ExpansionContext, parameter: String, operation: AssignDefaultOp, opCtx: ParameterOpContext, ewp: ExpandWordPartsFn): String { val ud = opCtx.isUnset || (operation.checkEmpty && opCtx.isEmpty); if (ud) { val dv = ewp(ctx, operation.word.parts, opCtx.inDoubleQuotes); ctx.state.env[parameter] = dv; return dv }; return opCtx.effectiveValue }
fun handleErrorIfUnset(ctx: ExpansionContext, parameter: String, operation: ErrorIfUnsetOp, opCtx: ParameterOpContext, ewp: ExpandWordPartsFn): String { val se = opCtx.isUnset || (operation.checkEmpty && opCtx.isEmpty); if (se) { val msg = if (operation.word != null) ewp(ctx, operation.word.parts, opCtx.inDoubleQuotes) else "$parameter: parameter null or not set"; throw ExitError(1, stderr = "bash: $msg\n") }; return opCtx.effectiveValue }
fun handleUseAlternative(ctx: ExpansionContext, operation: UseAlternativeOp, opCtx: ParameterOpContext, ewp: ExpandWordPartsFn): String { val ua = !(opCtx.isUnset || (operation.checkEmpty && opCtx.isEmpty)); return if (ua) ewp(ctx, operation.word.parts, opCtx.inDoubleQuotes) else "" }
fun handleLength(ctx: ExpansionContext, parameter: String, value: String): String { val am = Regex("^([a-zA-Z_][a-zA-Z0-9_]*)\\[[@*]\\]$").find(parameter); if (am != null) { val an = am.groupValues[1]; val els = getArrayElements(ctx, an); if (els.isNotEmpty()) return els.size.toString(); val sv = ctx.state.env[an]; return if (sv != null) "1" else "0" }; if (parameter.matches(Regex("^[a-zA-Z_][a-zA-Z0-9_]*$")) && isArray(ctx, parameter)) { val fe = getArrayElement(ctx, parameter, 0) ?: ""; return fe.length.toString() }; return value.length.toString() }

fun handlePatternRemoval(ctx: ExpansionContext, value: String, operation: PatternRemovalOp, ewp: ExpandWordPartsFn, ep: ExpandPartFn): String { val extglob = ctx.state.shoptOptions.extglob; var rs = ""; if (operation.pattern != null) { for (part in operation.pattern.parts) { when (part) { is GlobPart -> rs += patternToRegex(part.pattern, operation.greedy, extglob); is LiteralPart -> rs += patternToRegex(part.value, operation.greedy, extglob); is SingleQuotedPart -> rs += escapeRegex(part.value); is EscapedPart -> rs += escapeRegex(part.value); is DoubleQuotedPart -> { rs += escapeRegex(ewp(ctx, part.parts, false)) }; is ParameterExpansionPart -> { rs += patternToRegex(ep(ctx, part, false), operation.greedy, extglob) }; else -> { rs += escapeRegex(ep(ctx, part, false)) } } } }; return applyPatternRemoval(ctx, value, rs, operation.side, operation.greedy) }

fun handlePatternReplacement(ctx: ExpansionContext, value: String, operation: PatternReplacementOp, ewp: ExpandWordPartsFn, ep: ExpandPartFn): String { var regex = ""; val extglob = ctx.state.shoptOptions.extglob; if (operation.pattern != null) { for (part in operation.pattern.parts) { when (part) { is GlobPart -> regex += patternToRegex(part.pattern, true, extglob); is LiteralPart -> regex += patternToRegex(part.value, true, extglob); is SingleQuotedPart -> regex += escapeRegex(part.value); is EscapedPart -> regex += escapeRegex(part.value); is DoubleQuotedPart -> { regex += escapeRegex(ewp(ctx, part.parts, false)) }; is ParameterExpansionPart -> { regex += patternToRegex(ep(ctx, part, false), true, extglob) }; else -> { regex += escapeRegex(ep(ctx, part, false)) } } } }; val replacement = operation.replacement?.let { ewp(ctx, it.parts, false) } ?: ""; var rp = regex; if (operation.anchor == "start") rp = "^$regex"; else if (operation.anchor == "end") rp = "$regex\$"; if (rp == "") return value; try { val re = Regex(rp, setOf(RegexOption.DOT_MATCHES_ALL)); return applyPatternReplacementBounded(ctx, value, re, replacement, operation.all) } catch (e: Exception) { if (e is ExecutionLimitError) throw e; return value } }

fun handleSubstring(ctx: ExpansionContext, parameter: String, value: String, operation: SubstringOp): String { val offset = evaluateArithmetic(ctx, operation.offset.expression).toInt(); val length = operation.length?.let { evaluateArithmetic(ctx, it.expression).toInt() }; val chars = value.toList(); var start = offset; if (start < 0) start = Math.max(0, chars.size + start); if (length != null) { if (length < 0) { val endPos = chars.size + length; return chars.subList(start, Math.max(start, endPos)).joinToString("") }; return chars.subList(start, Math.min(chars.size, start + length)).joinToString("") }; return chars.subList(start, chars.size).joinToString("") }

fun handleCaseModification(ctx: ExpansionContext, value: String, operation: CaseModificationOp, ewp: ExpandWordPartsFn, expandParameter: ExpandParameterFn): String { if (operation.pattern != null) { val extglob = ctx.state.shoptOptions.extglob; var prs = ""; for (part in operation.pattern.parts) { when (part) { is GlobPart -> prs += patternToRegex(part.pattern, true, extglob); is LiteralPart -> prs += patternToRegex(part.value, true, extglob); is SingleQuotedPart -> prs += escapeRegex(part.value); is EscapedPart -> prs += escapeRegex(part.value); is DoubleQuotedPart -> { prs += escapeRegex(ewp(ctx, part.parts, false)) }; is ParameterExpansionPart -> { prs += patternToRegex(expandParameter(ctx, part, false), true, extglob) }; else -> {} } }; val cp = try { Regex("^(?:$prs)\$") } catch (e: Exception) { Regex("^$") }; val t: (String) -> String = if (operation.direction == "upper") ({ it.uppercase() }) else ({ it.lowercase() }); var result = ""; var converted = false; for (char in value) { val ch = char.toString(); if (!operation.all && converted) result += ch; else if (cp.matches(ch)) { result += t(ch); converted = true } else result += ch }; return result }; if (operation.direction == "upper") return if (operation.all) value.uppercase() else value.firstOrNull()?.uppercase().orEmpty() + value.drop(1); return if (operation.all) value.lowercase() else value.firstOrNull()?.lowercase().orEmpty() + value.drop(1) }

fun handleTransform(ctx: ExpansionContext, parameter: String, value: String, isUnset: Boolean, operation: TransformOp): String = when (operation.operator) { "Q" -> if (isUnset) "" else quoteValue(value); "P" -> expandPrompt(ctx, value); "a" -> getVariableAttributes(ctx, parameter); "A" -> if (isUnset) "" else "$parameter=${quoteValue(value)}"; "E" -> value.replace(Regex("\\\\([\\\\abefnrtv'\"?])")) { m -> when (m.groupValues[1]) { "\\" -> "\\"; "a" -> "\u0007"; "b" -> "\b"; "e" -> "\u001b"; "f" -> "\u000c"; "n" -> "\n"; "r" -> "\r"; "t" -> "\t"; "v" -> "\u000b"; else -> m.groupValues[1] } }; "K","k" -> if (isUnset) "" else quoteValue(value); "u" -> value.firstOrNull()?.uppercase().orEmpty() + value.drop(1); "U" -> value.uppercase(); "L" -> value.lowercase(); else -> value }

fun handleIndirection(ctx: ExpansionContext, parameter: String, value: String, isUnset: Boolean, operation: IndirectionOp, expandParameter: ExpandParameterFn, inDoubleQuotes: Boolean): String { if (ctx.state.namerefs.contains(parameter)) return getNamerefTarget(ctx, parameter) ?: ""; if (isUnset) { if (operation.innerOp is UseAlternativeOp) return ""; throw BadSubstitutionError("\${!$parameter}") }; if (operation.innerOp != null) { val sp = ParameterExpansionPart(value, operation.innerOp); return expandParameter(ctx, sp, inDoubleQuotes) }; return getVariable(ctx, value) }
fun handleArrayKeys(ctx: ExpansionContext, operation: ArrayKeysOp): String { val els = getArrayElements(ctx, operation.array); val keys = els.map { (k, _) -> k.toString() }; return if (operation.star) keys.joinToString(getIfsSeparator(ctx.state.env)) else keys.joinToString(" ") }
fun handleVarNamePrefix(ctx: ExpansionContext, operation: VarNamePrefixOp): String { val mv = getVarNamesWithPrefix(ctx, operation.prefix); return if (operation.star) mv.joinToString(getIfsSeparator(ctx.state.env)) else mv.joinToString(" ") }
