package com.justbash.interpreter.expansion

private val POSIX_CLASSES = mapOf("alnum" to "a-zA-Z0-9", "alpha" to "a-zA-Z", "ascii" to "\\x00-\\x7F", "blank" to " \\t", "cntrl" to "\\x00-\\x1F\\x7F", "digit" to "0-9", "graph" to "!-~", "lower" to "a-z", "print" to " -~", "punct" to "!-/:-@\\[-`{-~", "space" to " \\t\\n\\r\\f\\v", "upper" to "A-Z", "word" to "a-zA-Z0-9_", "xdigit" to "0-9A-Fa-f")

fun patternToRegex(pattern: String, greedy: Boolean, extglob: Boolean = false): String {
    val regex = StringBuilder(); var i = 0
    while (i < pattern.length) { val char = pattern[i]
        if (extglob && (char == '@' || char == '*' || char == '+' || char == '?' || char == '!') && i + 1 < pattern.length && pattern[i + 1] == '(') { val ci = findMatchingParen(pattern, i + 1); if (ci != -1) { val content = pattern.substring(i + 2, ci); val alternatives = splitExtglobAlternatives(content); val altRegexes = alternatives.map { patternToRegex(it, greedy, extglob) }; val altGroup = if (altRegexes.isNotEmpty()) altRegexes.joinToString("|") else "(?:)"; when (char) { '@' -> regex.append("(?:$altGroup)"); '*' -> regex.append("(?:$altGroup)*"); '+' -> regex.append("(?:$altGroup)+"); '?' -> regex.append("(?:$altGroup)?"); '!' -> regex.append("(?!(?:$altGroup)\$).*") }; i = ci + 1; continue } }
        when { char == '\\' -> { if (i + 1 < pattern.length) { val next = pattern[i + 1]; if ("\\^$.|+(){}[]*?".contains(next)) regex.append("\\$next") else regex.append(next); i += 2 } else { regex.append("\\\\"); i++ } } char == '*' -> { regex.append(if (greedy) ".*" else ".*?"); i++ } char == '?' -> { regex.append("."); i++ } char == '[' -> { val ce = findCharClassEnd(pattern, i); if (ce == -1) { regex.append("\\["); i++ } else { regex.append(convertCharClass(pattern.substring(i + 1, ce))); i = ce + 1 } } char in "^$.|+(){}" -> { regex.append("\\$char"); i++ } else -> { regex.append(char); i++ } }
    }
    return regex.toString()
}
private fun findMatchingParen(pattern: String, openIdx: Int): Int { var depth = 1; var i = openIdx + 1; while (i < pattern.length && depth > 0) { val c = pattern[i]; if (c == '\\') { i += 2; continue }; if (c == '(') depth++; else if (c == ')') { depth--; if (depth == 0) return i }; i++ }; return -1 }
private fun splitExtglobAlternatives(content: String): List<String> { val alts = ArrayList<String>(); val cur = StringBuilder(); var depth = 0; var i = 0; while (i < content.length) { val c = content[i]; if (c == '\\') { cur.append(c); if (i + 1 < content.length) { cur.append(content[i + 1]); i += 2 } else { i++ }; continue }; if (c == '(') { depth++; cur.append(c) } else if (c == ')') { depth--; cur.append(c) } else if (c == '|' && depth == 0) { alts.add(cur.toString()); cur.clear() } else { cur.append(c) }; i++ }; alts.add(cur.toString()); return alts }
private fun findCharClassEnd(pattern: String, start: Int): Int { var i = start + 1; if (i < pattern.length && pattern[i] == '^') i++; if (i < pattern.length && pattern[i] == ']') i++; while (i < pattern.length) { if (pattern[i] == '\\' && i + 1 < pattern.length) { i += 2; continue }; if (pattern[i] == ']') return i; if (pattern[i] == '\'') { val cq = pattern.indexOf('\'', i + 1); if (cq != -1) { i = cq + 1; continue } }; if (pattern[i] == '[' && i + 1 < pattern.length && pattern[i + 1] == ':') { val cp = pattern.indexOf(":]", i + 2); if (cp != -1) { i = cp + 2; continue } }; i++ }; return -1 }
private fun convertCharClass(content: String): String { val result = StringBuilder("["); var i = 0; if (content.isNotEmpty() && (content[0] == '^' || content[0] == '!')) { result.append("^"); i++ }; while (i < content.length) { if (content[i] == '\'') { val cq = content.indexOf('\'', i + 1); if (cq != -1) { val quoted = content.substring(i + 1, cq); for (ch in quoted) { when { ch == '\\' -> result.append("\\\\"); ch == ']' -> result.append("\\]"); ch == '^' && result.toString() == "[" -> result.append("\\^"); else -> result.append(ch) } }; i = cq + 1; continue } }; if (content[i] == '[' && i + 1 < content.length && content[i + 1] == ':') { val cp = content.indexOf(":]", i + 2); if (cp != -1) { result.append(POSIX_CLASSES[content.substring(i + 2, cp)] ?: ""); i = cp + 2; continue } }; val char = content[i]; when { char == '\\' -> { if (i + 1 < content.length) { result.append("\\${content[i + 1]}"); i += 2 } else { result.append("\\\\"); i++ } } char == '-' && i > 0 && i < content.length - 1 -> { result.append("-"); i++ } char == '^' && i == 0 -> { result.append("^"); i++ } else -> { if (char == ']' && i == 0) result.append("\\]") else result.append(char); i++ } } }; result.append("]"); return result.toString() }
